### ISSUE TITLE
css-loader 的版本似乎有问题呀？

### ISSUE THREAD

**Issue by hjw33210** [SpanJinChen/Vue-admin#16]
Error
Module build failed (from ./node_modules/css-loader/dist/cjs.js): ValidationError: Invalid options object. CSS Loader has been initialized using an options object that does not match the API schema. - options.modules has an unknown property 'compileType'. These properties are valid: object { auto?, mode?, exportGlobals?, localIdentName?, localIdentRegExp?, context?, hashPrefix?, getLocalIdent? } at validate (D:\src\node\Vue-admin\node_modules\css-loader\node_modules\schema-utils\dist\validate.js:98:11) at Object.loader (D:\src\node\Vue-admin\node_modules\css-loader\dist\index.js:36:28)

**Comment by jasonhui512** [comment]
npm install --dev css-loader@^5.0.0 postcss@^8.1.10 postcss-import@^13.0.0 postcss-loader@^4.1.0 postcss-url@^10.1.1 
可解决该问题
